chore(vpn): Build openconnect from scratch

diff --git a/vpn/Dockerfile b/vpn/Dockerfile
--- a/vpn/Dockerfile
+++ b/vpn/Dockerfile
@@ -6,7 +6,6 @@ ARG ALPINE_VERSION=3.11.5
 FROM alpine:${ALPINE_VERSION}
 
 LABEL openconnect.documentation="https://www.infradead.org/openconnect/index.html"
-
 #
 # VERY IMPORTANT: In order for our entrypoint/command scripts to receive signal to stop, we need to specify that through STOPSIGNAL
 #
@@ -18,6 +17,7 @@ ARG VPN_GROUP
 ARG VPN_PASSWORD
 ARG VPN_USER
 ARG VPN_PROTECTED_ROUTES
+ARG VPN_CERT_HASH
 
 ENV LANG=en_US.UTF-8
 ENV TZ=UTC
@@ -27,42 +27,22 @@ ENV BUILDTIME_VPN_USER=${VPN_USER}
 ENV BUILDTIME_VPN_PASSWORD=${VPN_PASSWORD}
 ENV BUILDTIME_VPN_GROUP=${VPN_GROUP}
 ENV BUILDTIME_VPN_PROTECTED_ROUTES=${VPN_PROTECTED_ROUTES}
+ENV BUILDTIME_VPN_CERT_HASH=${VPN_CERT_HASH}
 
 ENV OPENCONNECT_TIMESTAMP=true
 ENV OPENCONNECT_VERBOSE=false
 ENV OPENCONNECT_NON-INTER=true
 
-RUN apk upgrade --no-cache
-
+# Refresh apk index
+RUN apk --update --no-progress  --no-cache upgrade
 RUN apk add \
-    openconnect=8.05-r1 \
     dos2unix \
     supervisor \
     tini=0.18.0-r0 \
     --no-cache  --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/
 
-#
-# For a more advanced control over routing, uncomment this and also use the vpn-slice commented line in the connect-to-vpn.sh script
-#
-#  RUN apk add --no-cache \
-#     build-base \
-#     python3 \
-#     python3-dev \
-#     bind-tools \
-#   && pip3 install --no-cache-dir --upgrade pip \
-#   && rm -rf /var/cache/* \
-#   && rm -rf /root/.cache/*
-
-# RUN cd /usr/bin \
-#   && ln -sf python3 python \
-#   && ln -sf pip3 pip
-
-# RUN mkdir -p /deps
-# COPY /deps/vpn-slice-master.zip /deps/vpn-slice.zip
-# RUN pip3 install /deps/vpn-slice.zip
 
 # always add the docker DNS server
-
 RUN grep -qxF 'nameserver 127.0.0.11' /etc/resolv.conf || echo 'nameserver 127.0.0.11' >> /etc/resolv.conf
 COPY supervisord/supervisord.conf /etc/supervisor/supervisord.conf
 COPY scripts/connect-to-vpn.sh /usr/bin/connect-to-vpn.sh
@@ -71,10 +51,43 @@ COPY scripts/connect-to-vpn.sh /usr/bin/connect-to-vpn.sh
 # https://www.infradead.org/openconnect/vpnc-script.html
 
 COPY scripts/vpnc-script /etc/vpnc/vpnc-script
-
 RUN dos2unix /usr/bin/connect-to-vpn.sh
-# RUN dos2unix /etc/vpnc/vpnc-script
+RUN dos2unix /etc/vpnc/vpnc-script
 RUN chmod +x /usr/bin/connect-to-vpn.sh
 RUN chmod 755 /etc/vpnc/vpnc-script
+
+RUN mkdir -p /tmp/build/openconnect
+COPY deps/libs/openconnect-8.10.tar.gz /tmp/openconnect.tar.gz
+RUN tar -xf /tmp/openconnect.tar.gz -C /tmp/build/openconnect --strip-components=1
+
+RUN set -ex \
+
+            ## Install runtime dependencies
+
+            && apk add --no-progress --virtual .openconnect-run-deps \
+                    gnutls gnutls-utils iptables libev libintl \
+                    libnl3 libseccomp linux-pam openssl \
+                    libxml2 nmap-ncat socat openssh-client \
+                    openssl-dev p11-kit libproxy libproxy-dev \
+
+            ## Install build dependencies - these are deleted after the build
+
+            && apk add --no-progress --virtual .openconnect-build-deps \
+                    curl file g++ gnutls-dev gpgme gzip libev-dev \
+                    libnl3-dev libseccomp-dev libxml2-dev  linux-headers \
+                    linux-pam-dev make readline-dev tar \
+                    sed readline procps \
+
+            ## Build and install
+
+            && cd /tmp/build/openconnect \
+            && ./configure \
+            && make \
+            && make install \
+            && cd / \
+
+            # Cleanup
+
+            && apk del .openconnect-build-deps
 
 ENTRYPOINT ["/sbin/tini", "--", "/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
